// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation HomeController
@end

@implementation SettingController
@end

@implementation TweetsViewController
@end

@implementation SettingView
@end

