// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface HomeController: UIViewController
-(IBAction) init;

@end

@interface SettingController: UIViewController
-(IBAction) init;
-(IBAction) viewDidLoad;

@end

@interface TweetsViewController: UIViewController
-(IBAction) viewDidLoad;
-(IBAction) userTweet;
-(IBAction) toolbar;
-(IBAction) nextTweetButton;
-(IBAction) userImage;
-(IBAction) userName;
-(IBAction) userBio;

@end

@interface SettingView: UIView
-(IBAction) initWithFrame:(id) frame;
-(IBAction) textFieldShouldReturn:(id) textField;

@end

